### ISSUE TITLE
Tests failing in opt-js brankch

### ISSUE THREAD

**Issue by metabench** [mateogianolio/vectorious#16]
I just copied over the tests, but I get a lot of test fails...

```
C:\Users\James\Documents\GitHub\vectorious>mocha


  Vector
    .add()
      V should return empty vector if adding two empty vectors
      1) should throw error if sizes do not match
      V should work as expected
    .subtract()
      V should return empty vector if subtracting two empty vectors
      2) should throw error if sizes do not match
      V should work as expected
    .scale()
      V should work as expected
    .normalize()
      3) should work as expected
    .project()
      4) should throw error if sizes do not match
      5) should work as expected
    .zeros()
      V should throw error if argument < 0
      V should return empty vector if argument === 0
      V should work as expected
    .ones()
      V should throw error if argument < 0
      V should return empty vector if argument === 0
      V should work as expected
    .range()
      6) should throw error if wrong number or arguments supplied
      7) should throw error if step > start - end
      8) should work as expected
    .dot()
      9) should throw error if sizes do not match
      V should work as expected
    .magnitude()
      10) should return 0 if empty vector
      V should work as expected
    .angle()
      V should work as expected
    .equals()
      V should work as expected
    .get()
      11) should throw error if index out of bounds
      V should work as expected
    .min()
      V should work as expected
    .max()
      V should work as expected
    .set()
      12) should throw error if index out of bounds
      V should work as expected
    .combine()
      V should return current vector if combined with empty vector
      V should work as expected
    .push()
      V should work as expected
    .map()
      V should work as expected
    .each()
      V should work as expected
    .toString()
      V should work as expected
    .toArray()
      V should work as expected


  26 passing (31ms)
  12 failing

  1) Vector .add() should throw error if sizes do not match:
     Error: the string "Error: sizes do not match!" was thrown, throw an Er
      at Runner.fail (C:\Users\James\AppData\Roaming\npm\node_modules\mocha
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at done (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  2) Vector .subtract() should throw error if sizes do not match:
     Error: the string "Error: sizes do not match!" was thrown, throw an Er
      at Runner.fail (C:\Users\James\AppData\Roaming\npm\node_modules\mocha
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at done (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  3) Vector .normalize() should work as expected:
     AssertionError: { values: [ 0.7071067811865475, 0.7071067811865475 ],
  length: 2 } deepEqual { values: [ 0.5, 0.5 ], length: 2 }
      at Context.<anonymous> (C:\Users\James\Documents\GitHub\vectorious\te
      at callFn (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  4) Vector .project() should throw error if sizes do not match:
     Error: the string "Error: sizes do not match!" was thrown, throw an Er
      at Runner.fail (C:\Users\James\AppData\Roaming\npm\node_modules\mocha
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at done (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  5) Vector .project() should work as expected:
     AssertionError: { values: [ 0.24, -0.32 ], length: 2 } deepEqual { val
      at Context.<anonymous> (C:\Users\James\Documents\GitHub\vectorious\te
      at callFn (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  6) Vector .range() should throw error if wrong number or arguments suppli
     Error: the string "Error: invalid range!" was thrown, throw an Error :
      at Runner.fail (C:\Users\James\AppData\Roaming\npm\node_modules\mocha
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at done (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  7) Vector .range() should throw error if step > start - end:
     Error: the string "Error: invalid range!" was thrown, throw an Error :
      at Runner.fail (C:\Users\James\AppData\Roaming\npm\node_modules\mocha
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at done (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  8) Vector .range() should work as expected:
     AssertionError: { values: [ 0, 1, 2, 3, 4 ], length: 5 } deepEqual { v
      at Context.<anonymous> (C:\Users\James\Documents\GitHub\vectorious\te
      at callFn (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  9) Vector .dot() should throw error if sizes do not match:
     Error: the string "Error: sizes do not match!" was thrown, throw an Er
      at Runner.fail (C:\Users\James\AppData\Roaming\npm\node_modules\mocha
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at done (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  10) Vector .magnitude() should return 0 if empty vector:
     TypeError: Reduce of empty array with no initial value
      at Array.reduce (native)
      at Vector.magnitude (C:\Users\James\Documents\GitHub\vectorious\vecto
      at Context.<anonymous> (C:\Users\James\Documents\GitHub\vectorious\te
      at callFn (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  11) Vector .get() should throw error if index out of bounds:
     AssertionError: Missing expected exception (Error)..
      at Function._throws (assert.js:306:5)
      at Function.assert.throws (assert.js:323:11)
      at Context.<anonymous> (C:\Users\James\Documents\GitHub\vectorious\te
      at callFn (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

  12) Vector .set() should throw error if index out of bounds:
     AssertionError: Missing expected exception (Error)..
      at Function._throws (assert.js:306:5)
      at Function.assert.throws (assert.js:323:11)
      at Context.<anonymous> (C:\Users\James\Documents\GitHub\vectorious\te
      at callFn (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\
      at Test.Runnable.run (C:\Users\James\AppData\Roaming\npm\node_modules
      at Runner.runTest (C:\Users\James\AppData\Roaming\npm\node_modules\mo
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\runner.j
      at next (C:\Users\James\AppData\Roaming\npm\node_modules\mocha\lib\ru
      at Immediate._onImmediate (C:\Users\James\AppData\Roaming\npm\node_mo
      at processImmediate [as _immediateCallback] (timers.js:357:17)

```

Are the tests working for you on the `opt-js` branch? I don't think all these errors should be thrown, I'm not sure what's going on here.

**Comment by mateogianolio** [comment]
I just pushed your optimisations combined with some bug fixes and proper exception handling to opt-js. Can you confirm that tests are working now?

**Comment by metabench** [comment]
I just looked it it, it looks much better than master was.

One thing I question is the variable name `copy` because it's not an actual copy. How about we call it `res` or `result`?

I'll run the tests soon.

**Comment by metabench** [comment]
I tested it. All the tests pass :)
